In [121]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [46]:
# Q1: Create a DataFrame with the following e-commerce sales data:
# Columns: OrderID, CustomerID, Product, Category, Quantity, Price, OrderDate, Rating, Review
# Create at least 50 sample records with realistic data including dates from 2023-2024
# Display the first 10 and last 5 records using head() and tail()



df = pd.DataFrame({
    "OrderID": [101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125],

    "CustomerID": [201,202,203,204,205,206,207,208,209,210,205,206,207,208,209,210,211,212,213,214,215,202,201,203,204],

    "Product": ["Laptop","Mouse","Keyboard","Monitor","Headphones","Laptop","Mouse","Keyboard","Monitor","Headphones",
                "Tablet","Charger","Camera","Printer","Speaker","Tablet","Charger","Camera","Printer","Speaker",
                "Smartphone","Power Bank","Router","Webcam","SSD"],

    "Category": ["Electronics","Accessories","Accessories","Electronics","Accessories",
                 "Electronics","Accessories","Accessories","Electronics","Accessories",
                 "Electronics","Accessories","Electronics","Electronics","Accessories",
                 "Electronics","Accessories","Electronics","Electronics","Accessories",
                 "Electronics","Accessories","Electronics","Accessories","Electronics"],

    "Quantity": [1,2,1,1,2,1,3,1,2,1,
                 1,2,1,1,2,1,1,2,1,1,
                 1,2,1,1,2],

    "Price": [65000,500,1500,12000,2500,
              64000,450,1400,11500,2600,
              30000,800,45000,15000,4000,
              29000,750,44000,15500,4200,
              55000,1200,3500,3000,6000],

    "OrderDate": ["2023-01-15","2023-02-10","2023-03-05","2023-04-12","2023-05-18",
                  "2023-06-22","2023-07-08","2023-08-14","2023-09-01","2023-10-09",
                  "2023-11-20","2023-12-02","2024-01-11","2024-02-19","2024-03-03",
                  "2024-04-10","2024-05-16","2024-06-21","2024-07-07","2024-08-15",
                  "2024-09-05","2024-10-13","2024-11-09","2024-12-01","2024-12-20"],

    "Rating": [5,4,4,5,3,5,4,4,5,4,
               4,3,5,4,4,5,4,5,4,4,
               5,4,4,3,5],

    "Review": ["Excellent","Good","Good","Excellent","Average",
               "Excellent","Good","Good","Excellent","Good",
               "Good","Average","Excellent","Good","Good",
               "Excellent","Good","Excellent","Good","Good",
               "Excellent","Good","Good","Average","Excellent"]
})

print("Top 10 records:",df.head(10))

print("Last 5 records:",df.tail(5))

Top 10 records:    OrderID  CustomerID     Product     Category  Quantity  Price   OrderDate  \
0      101         201      Laptop  Electronics         1  65000  2023-01-15   
1      102         202       Mouse  Accessories         2    500  2023-02-10   
2      103         203    Keyboard  Accessories         1   1500  2023-03-05   
3      104         204     Monitor  Electronics         1  12000  2023-04-12   
4      105         205  Headphones  Accessories         2   2500  2023-05-18   
5      106         206      Laptop  Electronics         1  64000  2023-06-22   
6      107         207       Mouse  Accessories         3    450  2023-07-08   
7      108         208    Keyboard  Accessories         1   1400  2023-08-14   
8      109         209     Monitor  Electronics         2  11500  2023-09-01   
9      110         210  Headphones  Accessories         1   2600  2023-10-09   

   Rating     Review  
0       5  Excellent  
1       4       Good  
2       4       Good  
3       5  

In [47]:
# Q2: Use info() and describe() to get a comprehensive overview of the dataset
# Identify data types, missing values, and statistical summary
# Print the column names using columns attribute and shape of the dataset

#Info
print(df.info())

#Decribe
print(df.describe())

#Column Names
print("\nColumn Names are:",df.columns)


#Shape of Dataset
print("\n Shape of Dataset is:",df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   OrderID     25 non-null     int64 
 1   CustomerID  25 non-null     int64 
 2   Product     25 non-null     object
 3   Category    25 non-null     object
 4   Quantity    25 non-null     int64 
 5   Price       25 non-null     int64 
 6   OrderDate   25 non-null     object
 7   Rating      25 non-null     int64 
 8   Review      25 non-null     object
dtypes: int64(5), object(4)
memory usage: 1.9+ KB
None
          OrderID  CustomerID  Quantity         Price     Rating
count   25.000000   25.000000  25.00000     25.000000  25.000000
mean   113.000000  207.000000   1.40000  16736.000000   4.240000
std      7.359801    4.082483   0.57735  21309.585676   0.663325
min    101.000000  201.000000   1.00000    450.000000   3.000000
25%    107.000000  204.000000   1.00000   1500.000000   4.000000
50%    113.00

In [48]:
#Missing Values
df.isna()

OrderID  CustomerID  Product  Category  Quantity  Price  OrderDate  \
0     False       False    False     False     False  False      False   
1     False       False    False     False     False  False      False   
2     False       False    False     False     False  False      False   
3     False       False    False     False     False  False      False   
4     False       False    False     False     False  False      False   
5     False       False    False     False     False  False      False   
6     False       False    False     False     False  False      False   
7     False       False    False     False     False  False      False   
8     False       False    False     False     False  False      False   
9     False       False    False     False     False  False      False   
10    False       False    False     False     False  False      False   
11    False       False    False     False     False  False      False   
12    False       False    False     False     False  False      False   
13    False       False    False     False     False  False      False   
14    False       False    False     False     False  False      False   
15    False       False    False     False     False  False      False   
16    False       False    False     False     False  False      False   
17    False       False    False     False     False  False      False   
18    False       False    False     False     False  False      False   
19    False       False    False     False     False  False      False   
20    False       False    False     False     False  False      False   
21    False       False    False     False     False  False      False   
22    False       False    False     False     False  False      False   
23    False       False    False     False     False  False      False   
24    False       False    False     False     False  False      False   

    Rating  Review  
0    False   False  
1    False   False  
2    False   False  
3    False   False  
4    False   False  
5    False   False  
6    False   False  
7    False   False  
8    False   False  
9    False   False  
10   False   False  
11   False   False  
12   False   False  
13   False   False  
14   False   False  
15   False   False  
16   False   False  
17   False   False  
18   False   False  
19   False   False  
20   False   False  
21   False   False  
22   False   False  
23   False   False  
24   False   False

In [ ]:
# Q3: Introduce 10% missing values randomly in Rating and Review columns
# Detect missing values and display the count of missing values per column



df.loc[2,"Rating"]=None
df.loc[16,"Rating"]=None
df.loc[23,"Rating"]=None
df.loc[5,"Review"]=None
df.loc[19,"Review"]=None
df.loc[24,"Review"]=None

df.isna().any()


OrderID       False
CustomerID    False
Product       False
Category      False
Quantity      False
Price         False
OrderDate     False
Rating         True
Review         True
dtype: bool

In [50]:
df.isna().sum()


OrderID       0
CustomerID    0
Product       0
Category      0
Quantity      0
Price         0
OrderDate     0
Rating        3
Review        3
dtype: int64

In [51]:
# Calculate median of Rating column
medi = df["Rating"].median()
print(medi)

# Fill missing Rating values with median
df["Rating"] = df["Rating"].fillna(medi)

# Fill missing Review values
df["Review"] = df["Review"].fillna("No review provided")

df


4.0


OrderID  CustomerID     Product     Category  Quantity  Price   OrderDate  \
0       101         201      Laptop  Electronics         1  65000  2023-01-15   
1       102         202       Mouse  Accessories         2    500  2023-02-10   
2       103         203    Keyboard  Accessories         1   1500  2023-03-05   
3       104         204     Monitor  Electronics         1  12000  2023-04-12   
4       105         205  Headphones  Accessories         2   2500  2023-05-18   
5       106         206      Laptop  Electronics         1  64000  2023-06-22   
6       107         207       Mouse  Accessories         3    450  2023-07-08   
7       108         208    Keyboard  Accessories         1   1400  2023-08-14   
8       109         209     Monitor  Electronics         2  11500  2023-09-01   
9       110         210  Headphones  Accessories         1   2600  2023-10-09   
10      111         205      Tablet  Electronics         1  30000  2023-11-20   
11      112         206     Charger  Accessories         2    800  2023-12-02   
12      113         207      Camera  Electronics         1  45000  2024-01-11   
13      114         208     Printer  Electronics         1  15000  2024-02-19   
14      115         209     Speaker  Accessories         2   4000  2024-03-03   
15      116         210      Tablet  Electronics         1  29000  2024-04-10   
16      117         211     Charger  Accessories         1    750  2024-05-16   
17      118         212      Camera  Electronics         2  44000  2024-06-21   
18      119         213     Printer  Electronics         1  15500  2024-07-07   
19      120         214     Speaker  Accessories         1   4200  2024-08-15   
20      121         215  Smartphone  Electronics         1  55000  2024-09-05   
21      122         202  Power Bank  Accessories         2   1200  2024-10-13   
22      123         201      Router  Electronics         1   3500  2024-11-09   
23      124         203      Webcam  Accessories         1   3000  2024-12-01   
24      125         204         SSD  Electronics         2   6000  2024-12-20   

    Rating              Review  
0      5.0           Excellent  
1      4.0                Good  
2      4.0                Good  
3      5.0           Excellent  
4      3.0             Average  
5      5.0  No review provided  
6      4.0                Good  
7      4.0                Good  
8      5.0           Excellent  
9      4.0                Good  
10     4.0                Good  
11     3.0             Average  
12     5.0           Excellent  
13     4.0                Good  
14     4.0                Good  
15     5.0           Excellent  
16     4.0                Good  
17     5.0           Excellent  
18     4.0                Good  
19     4.0  No review provided  
20     5.0           Excellent  
21     4.0                Good  
22     4.0                Good  
23     4.0             Average  
24     5.0  No review provided

In [54]:
# Q4: Create a new column 'TotalAmount' by multiplying Quantity and Price

df['TotalAmount']=df['Quantity']*df['Price']
df

OrderID  CustomerID     Product     Category  Quantity  Price   OrderDate  \
0       101         201      Laptop  Electronics         1  65000  2023-01-15   
1       102         202       Mouse  Accessories         2    500  2023-02-10   
2       103         203    Keyboard  Accessories         1   1500  2023-03-05   
3       104         204     Monitor  Electronics         1  12000  2023-04-12   
4       105         205  Headphones  Accessories         2   2500  2023-05-18   
5       106         206      Laptop  Electronics         1  64000  2023-06-22   
6       107         207       Mouse  Accessories         3    450  2023-07-08   
7       108         208    Keyboard  Accessories         1   1400  2023-08-14   
8       109         209     Monitor  Electronics         2  11500  2023-09-01   
9       110         210  Headphones  Accessories         1   2600  2023-10-09   
10      111         205      Tablet  Electronics         1  30000  2023-11-20   
11      112         206     Charger  Accessories         2    800  2023-12-02   
12      113         207      Camera  Electronics         1  45000  2024-01-11   
13      114         208     Printer  Electronics         1  15000  2024-02-19   
14      115         209     Speaker  Accessories         2   4000  2024-03-03   
15      116         210      Tablet  Electronics         1  29000  2024-04-10   
16      117         211     Charger  Accessories         1    750  2024-05-16   
17      118         212      Camera  Electronics         2  44000  2024-06-21   
18      119         213     Printer  Electronics         1  15500  2024-07-07   
19      120         214     Speaker  Accessories         1   4200  2024-08-15   
20      121         215  Smartphone  Electronics         1  55000  2024-09-05   
21      122         202  Power Bank  Accessories         2   1200  2024-10-13   
22      123         201      Router  Electronics         1   3500  2024-11-09   
23      124         203      Webcam  Accessories         1   3000  2024-12-01   
24      125         204         SSD  Electronics         2   6000  2024-12-20   

    Rating              Review  TotalAmount  
0      5.0           Excellent        65000  
1      4.0                Good         1000  
2      4.0                Good         1500  
3      5.0           Excellent        12000  
4      3.0             Average         5000  
5      5.0  No review provided        64000  
6      4.0                Good         1350  
7      4.0                Good         1400  
8      5.0           Excellent        23000  
9      4.0                Good         2600  
10     4.0                Good        30000  
11     3.0             Average         1600  
12     5.0           Excellent        45000  
13     4.0                Good        15000  
14     4.0                Good         8000  
15     5.0           Excellent        29000  
16     4.0                Good          750  
17     5.0           Excellent        88000  
18     4.0                Good        15500  
19     4.0  No review provided         4200  
20     5.0           Excellent        55000  
21     4.0                Good         2400  
22     4.0                Good         3500  
23     4.0             Average         3000  
24     5.0  No review provided        12000

In [60]:
# Add another column 'DiscountedPrice' that applies 10% discount on orders above 10000
Discounted=[]
for i in df['TotalAmount']:
    if i>10000:
        Discounted.append(i-(i*0.1))
    else:
        Discounted.append(None)


df['DiscountedPrice']=Discounted
df

OrderID  CustomerID     Product     Category  Quantity  Price   OrderDate  \
0       101         201      Laptop  Electronics         1  65000  2023-01-15   
1       102         202       Mouse  Accessories         2    500  2023-02-10   
2       103         203    Keyboard  Accessories         1   1500  2023-03-05   
3       104         204     Monitor  Electronics         1  12000  2023-04-12   
4       105         205  Headphones  Accessories         2   2500  2023-05-18   
5       106         206      Laptop  Electronics         1  64000  2023-06-22   
6       107         207       Mouse  Accessories         3    450  2023-07-08   
7       108         208    Keyboard  Accessories         1   1400  2023-08-14   
8       109         209     Monitor  Electronics         2  11500  2023-09-01   
9       110         210  Headphones  Accessories         1   2600  2023-10-09   
10      111         205      Tablet  Electronics         1  30000  2023-11-20   
11      112         206     Charger  Accessories         2    800  2023-12-02   
12      113         207      Camera  Electronics         1  45000  2024-01-11   
13      114         208     Printer  Electronics         1  15000  2024-02-19   
14      115         209     Speaker  Accessories         2   4000  2024-03-03   
15      116         210      Tablet  Electronics         1  29000  2024-04-10   
16      117         211     Charger  Accessories         1    750  2024-05-16   
17      118         212      Camera  Electronics         2  44000  2024-06-21   
18      119         213     Printer  Electronics         1  15500  2024-07-07   
19      120         214     Speaker  Accessories         1   4200  2024-08-15   
20      121         215  Smartphone  Electronics         1  55000  2024-09-05   
21      122         202  Power Bank  Accessories         2   1200  2024-10-13   
22      123         201      Router  Electronics         1   3500  2024-11-09   
23      124         203      Webcam  Accessories         1   3000  2024-12-01   
24      125         204         SSD  Electronics         2   6000  2024-12-20   

    Rating              Review  TotalAmount  DiscountedPrice  
0      5.0           Excellent        65000          58500.0  
1      4.0                Good         1000              NaN  
2      4.0                Good         1500              NaN  
3      5.0           Excellent        12000          10800.0  
4      3.0             Average         5000              NaN  
5      5.0  No review provided        64000          57600.0  
6      4.0                Good         1350              NaN  
7      4.0                Good         1400              NaN  
8      5.0           Excellent        23000          20700.0  
9      4.0                Good         2600              NaN  
10     4.0                Good        30000          27000.0  
11     3.0             Average         1600              NaN  
12     5.0           Excellent        45000          40500.0  
13     4.0                Good        15000          13500.0  
14     4.0                Good         8000              NaN  
15     5.0           Excellent        29000          26100.0  
16     4.0                Good          750              NaN  
17     5.0           Excellent        88000          79200.0  
18     4.0                Good        15500          13950.0  
19     4.0  No review provided         4200              NaN  
20     5.0           Excellent        55000          49500.0  
21     4.0                Good         2400              NaN  
22     4.0                Good         3500              NaN  
23     4.0             Average         3000              NaN  
24     5.0  No review provided        12000          10800.0

In [62]:
# Use conditional selection to filter orders where TotalAmount > $150

cond=df[df["TotalAmount"]>1000]
print(cond)

    OrderID  CustomerID     Product     Category  Quantity  Price   OrderDate  \
0       101         201      Laptop  Electronics         1  65000  2023-01-15   
2       103         203    Keyboard  Accessories         1   1500  2023-03-05   
3       104         204     Monitor  Electronics         1  12000  2023-04-12   
4       105         205  Headphones  Accessories         2   2500  2023-05-18   
5       106         206      Laptop  Electronics         1  64000  2023-06-22   
6       107         207       Mouse  Accessories         3    450  2023-07-08   
7       108         208    Keyboard  Accessories         1   1400  2023-08-14   
8       109         209     Monitor  Electronics         2  11500  2023-09-01   
9       110         210  Headphones  Accessories         1   2600  2023-10-09   
10      111         205      Tablet  Electronics         1  30000  2023-11-20   
11      112         206     Charger  Accessories         2    800  2023-12-02   
12      113         207     

In [66]:
# Q5: Select only the columns: Product, Category, TotalAmount, and Rating
# Filter and display all orders from the 'Electronics' category with Rating >= 4



df2=df[['Product', 'Category', 'TotalAmount', 'Rating']]
cond2=df2[(df['Category']=='Electronics') & (df['Rating']>=4)]
cond2

Product     Category  TotalAmount  Rating
0       Laptop  Electronics        65000     5.0
3      Monitor  Electronics        12000     5.0
5       Laptop  Electronics        64000     5.0
8      Monitor  Electronics        23000     5.0
10      Tablet  Electronics        30000     4.0
12      Camera  Electronics        45000     5.0
13     Printer  Electronics        15000     4.0
15      Tablet  Electronics        29000     5.0
17      Camera  Electronics        88000     5.0
18     Printer  Electronics        15500     4.0
20  Smartphone  Electronics        55000     5.0
22      Router  Electronics         3500     4.0
24         SSD  Electronics        12000     5.0

In [ ]:
# Q6: Use boolean indexing to find all orders where:
# - Quantity > 2 AND Price < 50 OR Rating == 5

cond3 = df[((df["Quantity"] > 2) & (df["Price"] < 1000)) | (df["Rating"] == 5)]
cond3



OrderID  CustomerID     Product     Category  Quantity  Price   OrderDate  \
0       101         201      Laptop  Electronics         1  65000  2023-01-15   
3       104         204     Monitor  Electronics         1  12000  2023-04-12   
5       106         206      Laptop  Electronics         1  64000  2023-06-22   
6       107         207       Mouse  Accessories         3    450  2023-07-08   
8       109         209     Monitor  Electronics         2  11500  2023-09-01   
12      113         207      Camera  Electronics         1  45000  2024-01-11   
15      116         210      Tablet  Electronics         1  29000  2024-04-10   
17      118         212      Camera  Electronics         2  44000  2024-06-21   
20      121         215  Smartphone  Electronics         1  55000  2024-09-05   
24      125         204         SSD  Electronics         2   6000  2024-12-20   

    Rating              Review  TotalAmount  DiscountedPrice  
0      5.0           Excellent        65000          58500.0  
3      5.0           Excellent        12000          10800.0  
5      5.0  No review provided        64000          57600.0  
6      4.0                Good         1350              NaN  
8      5.0           Excellent        23000          20700.0  
12     5.0           Excellent        45000          40500.0  
15     5.0           Excellent        29000          26100.0  
17     5.0           Excellent        88000          79200.0  
20     5.0           Excellent        55000          49500.0  
24     5.0  No review provided        12000          10800.0

In [ ]:
# Display the count of such orders

print("Count of matching orders:", len(cond3))

Count of matching orders: 10


In [ ]:
# Q7: Sort the entire DataFrame by OrderDate (descending) and then by TotalAmount (descending)
 
sort=df.sort_values(by='OrderDate',ascending=False)
sort

OrderID  CustomerID     Product     Category  Quantity  Price   OrderDate  \
24      125         204         SSD  Electronics         2   6000  2024-12-20   
23      124         203      Webcam  Accessories         1   3000  2024-12-01   
22      123         201      Router  Electronics         1   3500  2024-11-09   
21      122         202  Power Bank  Accessories         2   1200  2024-10-13   
20      121         215  Smartphone  Electronics         1  55000  2024-09-05   
19      120         214     Speaker  Accessories         1   4200  2024-08-15   
18      119         213     Printer  Electronics         1  15500  2024-07-07   
17      118         212      Camera  Electronics         2  44000  2024-06-21   
16      117         211     Charger  Accessories         1    750  2024-05-16   
15      116         210      Tablet  Electronics         1  29000  2024-04-10   
14      115         209     Speaker  Accessories         2   4000  2024-03-03   
13      114         208     Printer  Electronics         1  15000  2024-02-19   
12      113         207      Camera  Electronics         1  45000  2024-01-11   
11      112         206     Charger  Accessories         2    800  2023-12-02   
10      111         205      Tablet  Electronics         1  30000  2023-11-20   
9       110         210  Headphones  Accessories         1   2600  2023-10-09   
8       109         209     Monitor  Electronics         2  11500  2023-09-01   
7       108         208    Keyboard  Accessories         1   1400  2023-08-14   
6       107         207       Mouse  Accessories         3    450  2023-07-08   
5       106         206      Laptop  Electronics         1  64000  2023-06-22   
4       105         205  Headphones  Accessories         2   2500  2023-05-18   
3       104         204     Monitor  Electronics         1  12000  2023-04-12   
2       103         203    Keyboard  Accessories         1   1500  2023-03-05   
1       102         202       Mouse  Accessories         2    500  2023-02-10   
0       101         201      Laptop  Electronics         1  65000  2023-01-15   

    Rating              Review  TotalAmount  DiscountedPrice  
24     5.0  No review provided        12000          10800.0  
23     4.0             Average         3000              NaN  
22     4.0                Good         3500              NaN  
21     4.0                Good         2400              NaN  
20     5.0           Excellent        55000          49500.0  
19     4.0  No review provided         4200              NaN  
18     4.0                Good        15500          13950.0  
17     5.0           Excellent        88000          79200.0  
16     4.0                Good          750              NaN  
15     5.0           Excellent        29000          26100.0  
14     4.0                Good         8000              NaN  
13     4.0                Good        15000          13500.0  
12     5.0           Excellent        45000          40500.0  
11     3.0             Average         1600              NaN  
10     4.0                Good        30000          27000.0  
9      4.0                Good         2600              NaN  
8      5.0           Excellent        23000          20700.0  
7      4.0                Good         1400              NaN  
6      4.0                Good         1350              NaN  
5      5.0  No review provided        64000          57600.0  
4      3.0             Average         5000              NaN  
3      5.0           Excellent        12000          10800.0  
2      4.0                Good         1500              NaN  
1      4.0                Good         1000              NaN  
0      5.0           Excellent        65000          58500.0

In [80]:
# Create a new column 'SalesRank' that ranks products by TotalAmount in descending order
df['SalesRank']=df["TotalAmount"].rank(ascending=False)
df


OrderID  CustomerID     Product     Category  Quantity  Price   OrderDate  \
0       101         201      Laptop  Electronics         1  65000  2023-01-15   
1       102         202       Mouse  Accessories         2    500  2023-02-10   
2       103         203    Keyboard  Accessories         1   1500  2023-03-05   
3       104         204     Monitor  Electronics         1  12000  2023-04-12   
4       105         205  Headphones  Accessories         2   2500  2023-05-18   
5       106         206      Laptop  Electronics         1  64000  2023-06-22   
6       107         207       Mouse  Accessories         3    450  2023-07-08   
7       108         208    Keyboard  Accessories         1   1400  2023-08-14   
8       109         209     Monitor  Electronics         2  11500  2023-09-01   
9       110         210  Headphones  Accessories         1   2600  2023-10-09   
10      111         205      Tablet  Electronics         1  30000  2023-11-20   
11      112         206     Charger  Accessories         2    800  2023-12-02   
12      113         207      Camera  Electronics         1  45000  2024-01-11   
13      114         208     Printer  Electronics         1  15000  2024-02-19   
14      115         209     Speaker  Accessories         2   4000  2024-03-03   
15      116         210      Tablet  Electronics         1  29000  2024-04-10   
16      117         211     Charger  Accessories         1    750  2024-05-16   
17      118         212      Camera  Electronics         2  44000  2024-06-21   
18      119         213     Printer  Electronics         1  15500  2024-07-07   
19      120         214     Speaker  Accessories         1   4200  2024-08-15   
20      121         215  Smartphone  Electronics         1  55000  2024-09-05   
21      122         202  Power Bank  Accessories         2   1200  2024-10-13   
22      123         201      Router  Electronics         1   3500  2024-11-09   
23      124         203      Webcam  Accessories         1   3000  2024-12-01   
24      125         204         SSD  Electronics         2   6000  2024-12-20   

    Rating              Review  TotalAmount  DiscountedPrice  SalesRank  
0      5.0           Excellent        65000          58500.0        2.0  
1      4.0                Good         1000              NaN       24.0  
2      4.0                Good         1500              NaN       21.0  
3      5.0           Excellent        12000          10800.0       11.5  
4      3.0             Average         5000              NaN       14.0  
5      5.0  No review provided        64000          57600.0        3.0  
6      4.0                Good         1350              NaN       23.0  
7      4.0                Good         1400              NaN       22.0  
8      5.0           Excellent        23000          20700.0        8.0  
9      4.0                Good         2600              NaN       18.0  
10     4.0                Good        30000          27000.0        6.0  
11     3.0             Average         1600              NaN       20.0  
12     5.0           Excellent        45000          40500.0        5.0  
13     4.0                Good        15000          13500.0       10.0  
14     4.0                Good         8000              NaN       13.0  
15     5.0           Excellent        29000          26100.0        7.0  
16     4.0                Good          750              NaN       25.0  
17     5.0           Excellent        88000          79200.0        1.0  
18     4.0                Good        15500          13950.0        9.0  
19     4.0  No review provided         4200              NaN       15.0  
20     5.0           Excellent        55000          49500.0        4.0  
21     4.0                Good         2400              NaN       19.0  
22     4.0                Good         3500              NaN       16.0  
23     4.0             Average         3000              NaN       17.0  
24     5.0  No review provided        12000    

In [83]:
# Q8: Find the top 5 best-selling products based on total quantity sold
top5=df.sort_values(by='Quantity',ascending=False)
top5.head(5)


OrderID  CustomerID     Product     Category  Quantity  Price   OrderDate  \
6       107         207       Mouse  Accessories         3    450  2023-07-08   
8       109         209     Monitor  Electronics         2  11500  2023-09-01   
1       102         202       Mouse  Accessories         2    500  2023-02-10   
4       105         205  Headphones  Accessories         2   2500  2023-05-18   
24      125         204         SSD  Electronics         2   6000  2024-12-20   

    Rating              Review  TotalAmount  DiscountedPrice  SalesRank  
6      4.0                Good         1350              NaN       23.0  
8      5.0           Excellent        23000          20700.0        8.0  
1      4.0                Good         1000              NaN       24.0  
4      3.0             Average         5000              NaN       14.0  
24     5.0  No review provided        12000          10800.0       11.5

In [84]:
# Display the product name and total quantity in descending order
df3=df[["Product","Quantity"]]
sort=df3.sort_values(by="Quantity",ascending=False)
sort

Product  Quantity
6        Mouse         3
8      Monitor         2
1        Mouse         2
4   Headphones         2
24         SSD         2
17      Camera         2
21  Power Bank         2
14     Speaker         2
11     Charger         2
7     Keyboard         1
5       Laptop         1
2     Keyboard         1
3      Monitor         1
0       Laptop         1
12      Camera         1
10      Tablet         1
9   Headphones         1
16     Charger         1
15      Tablet         1
13     Printer         1
18     Printer         1
20  Smartphone         1
19     Speaker         1
22      Router         1
23      Webcam         1

In [94]:
# Q9: Group the data by 'Category' and calculate:
# - Total sales (sum of TotalAmount)
# - Average rating
# - Number of orders
# Display the results sorted by total sales
grouped = df.groupby("Category").agg(TotalSales=("TotalAmount", "sum"),AverageRating=("Rating", "mean"),NumberOfOrders=("OrderID", "count"))

# Sort by total sales
grouped = grouped.sort_values(by="TotalSales", ascending=False)

print(grouped)


             TotalSales  AverageRating  NumberOfOrders
Category                                              
Electronics      457000       4.692308              13
Accessories       32800       3.833333              12


In [ ]:
# Q10: Create a pivot table showing average Price for each Category and Rating combination

pivot = pd.pivot_table(
    df,
    values="Price",
    index="Category",
    columns="Rating",
    aggfunc="mean"
)

print(pivot)


Rating          3.0      4.0           5.0
Category                                  
Accessories  1650.0   1960.0           NaN
Electronics     NaN  16000.0  36833.333333


In [96]:
# Use groupby with multiple columns (Category, Product) and aggregate multiple functions

group_multi = df.groupby(["Category", "Product"]).agg(
    AvgPrice=("Price", "mean"),
    TotalQuantity=("Quantity", "sum"),
    AvgRating=("Rating", "mean"),
    OrderCount=("OrderID", "count")
)

print(group_multi)

                        AvgPrice  TotalQuantity  AvgRating  OrderCount
Category    Product                                                   
Accessories Charger        775.0              3        3.5           2
            Headphones    2550.0              3        3.5           2
            Keyboard      1450.0              2        4.0           2
            Mouse          475.0              5        4.0           2
            Power Bank    1200.0              2        4.0           1
            Speaker       4100.0              3        4.0           2
            Webcam        3000.0              1        4.0           1
Electronics Camera       44500.0              3        5.0           2
            Laptop       64500.0              2        5.0           2
            Monitor      11750.0              3        5.0           2
            Printer      15250.0              2        4.0           2
            Router        3500.0              1        4.0           1
      

In [98]:
# Q11: Convert the Quantity and Price columns to NumPy arrays
# Create a 2D array combining these two columns
# Display array properties: shape, dtype, ndim, size

arr1=np.array(df['Quantity'])
arr1

array([1, 2, 1, 1, 2, 1, 3, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2,
       1, 1, 2])

In [100]:
arr2=np.array(df['Price'])
arr2

array([65000,   500,  1500, 12000,  2500, 64000,   450,  1400, 11500,
        2600, 30000,   800, 45000, 15000,  4000, 29000,   750, 44000,
       15500,  4200, 55000,  1200,  3500,  3000,  6000])

In [114]:
arr3 = np.column_stack((arr1, arr2))
print(arr3)

print("Shape:", arr3.shape)
print("Data type:", arr3.dtype)
print("Number of dimensions:", arr3.ndim)
print("Size:", arr3.size)


[[    1 65000]
 [    2   500]
 [    1  1500]
 [    1 12000]
 [    2  2500]
 [    1 64000]
 [    3   450]
 [    1  1400]
 [    2 11500]
 [    1  2600]
 [    1 30000]
 [    2   800]
 [    1 45000]
 [    1 15000]
 [    2  4000]
 [    1 29000]
 [    1   750]
 [    2 44000]
 [    1 15500]
 [    1  4200]
 [    1 55000]
 [    2  1200]
 [    1  3500]
 [    1  3000]
 [    2  6000]]
Shape: (25, 2)
Data type: int64
Number of dimensions: 2
Size: 50


In [112]:
# Q12: Create a 1D NumPy array of 100 random prices between 10 and 500
# Calculate mean, median, standard deviation, min, and max using NumPy functions
# Reshape this array into a 10x10 matrix

prices = np.random.uniform(10, 500, 100)

print("Mean:", np.mean(prices))
print("Median:", np.median(prices))
print("Std Dev:", np.std(prices))
print("Min:", np.min(prices))
print("Max:", np.max(prices))

matrix = prices.reshape(10, 10)
matrix


Mean: 230.6902686384722
Median: 240.5339694007547
Std Dev: 142.82781399054267
Min: 11.6907621195856
Max: 488.2682300357585


array([[427.76474845, 238.51633464, 230.38098688, 214.95459787,
        241.88328046, 479.76718741, 421.72728907, 106.23116133,
        144.13439101, 383.77052144],
       [164.443979  , 426.81731255,  36.24255493, 163.97365707,
        443.66385368, 172.85560541, 151.61743333, 314.06255304,
        412.05387853, 122.06822093],
       [ 97.89072349, 278.89424991,  36.1540854 ,  49.02844829,
        352.95751949,  23.70362276, 109.18838251, 239.18465834,
         32.82000437, 479.40746768],
       [295.03179453, 400.43073061, 451.46679729, 263.16011699,
        290.55172413, 399.04181294, 458.81667728, 445.36815016,
        218.59303695, 162.30106051],
       [ 17.92505088, 185.63906424, 284.26738172, 293.59438411,
        246.37600141, 306.20205993,  23.4287525 , 438.414765  ,
        388.64279365, 330.92517329],
       [250.68241813, 265.90119956, 261.0298783 , 488.26823004,
        414.93969656, 300.04572651,  48.4545164 , 429.79933553,
        157.1397282 ,  11.69076212],
       [38

In [115]:
# Q13: Create two 3D NumPy arrays (3x3x3) with random integers
# Perform element-wise addition, multiplication, and matrix multiplication
# Use boolean indexing to filter values greater than 50
import numpy as np

a = np.random.randint(1, 100, size=(3, 3, 3))
b = np.random.randint(1, 100, size=(3, 3, 3))

print("Array A:\n", a)
print("\nArray B:\n", b)


Array A:
 [[[13 95 77]
  [ 7 27 61]
  [ 5 78 18]]

 [[96 46 41]
  [57 65 90]
  [ 8 13 85]]

 [[89 54 60]
  [68 56  5]
  [86 15 18]]]

Array B:
 [[[45 88 40]
  [87 92 47]
  [50 42 60]]

 [[52 35 58]
  [72 62 75]
  [58 28 86]]

 [[48 56 48]
  [78  2 57]
  [53 73 47]]]


In [116]:
add=a+b
print("Addition:",add)

multi=a*b
print("Simple Mutiplication:",multi)

matmul = np.matmul(a, b)
print("\nMatrix Multiplication :\n", matmul)


Addition: [[[ 58 183 117]
  [ 94 119 108]
  [ 55 120  78]]

 [[148  81  99]
  [129 127 165]
  [ 66  41 171]]

 [[137 110 108]
  [146  58  62]
  [139  88  65]]]
Simple Mutiplication: [[[ 585 8360 3080]
  [ 609 2484 2867]
  [ 250 3276 1080]]

 [[4992 1610 2378]
  [4104 4030 6750]
  [ 464  364 7310]]

 [[4272 3024 2880]
  [5304  112  285]
  [4558 1095  846]]]

Matrix Multiplication :
 [[[12700 13118  9605]
  [ 5714  5662  5209]
  [ 7911  8372  4946]]

 [[10682  7360 12544]
  [12864  8545 15921]
  [ 6282  3466  8749]]

 [[11664  9472 10170]
  [ 7897  4285  6691]
  [ 6252  6160  5829]]]


In [118]:
# Use boolean indexing to filter values greater than 50
filtered = a[a > 50]
print("\nValues in A greater than 50:\n", filtered)



Values in A greater than 50:
 [95 77 61 78 96 57 65 90 85 89 54 60 68 56 86]


In [119]:
# Q14: Create NumPy arrays using special values:
# - Array of zeros (5x5)
# - Array of ones (3x4)
# - Identity matrix (4x4)
# - Array with values from 0 to 50 with step of 5 using arange
# Concatenate and stack these arrays

z = np.zeros((5, 5))
print("Zeros (5x5):\n", z)

o = np.ones((3, 4))
print("\nOnes (3x4):\n", o)

i = np.eye(4)
print("\nIdentity (4x4):\n", i)

a = np.arange(0, 51, 5)
print("\nArange array:\n", a)

concat = np.concatenate((z[:3, :4], o), axis=0)
print("\nConcatenated array:\n", concat)

stacked = np.stack((i, i), axis=0)
print("\nStacked array shape:", stacked.shape)
print(stacked)


Zeros (5x5):
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Ones (3x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Arange array:
 [ 0  5 10 15 20 25 30 35 40 45 50]

Concatenated array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Stacked array shape: (2, 4, 4)
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]


In [125]:
# Q15: Use array slicing to extract:
# - First 3 rows from the Quantity-Price 2D array
# - Every alternate element from the Price array
# - Diagonal elements from a 5x5 matrix of TotalAmount values

qty_price_arr = np.column_stack((df['Quantity'], df['Price']))
first3_rows = qty_price_arr[:3, :]  
print("First 3 rows:\n", first3_rows)

price_arr = np.array(df['Price'])  

alternate_price = price_arr[::2]  
print("\nEvery alternate price:\n", alternate_price)

total_mat = df['TotalAmount'].to_numpy()[:25].reshape(5, 5)
print("\n5x5 TotalAmount matrix:\n", total_mat)

diagonal_elements = np.diag(total_mat)
print("\nDiagonal elements:\n", diagonal_elements)



First 3 rows:
 [[    1 65000]
 [    2   500]
 [    1  1500]]

Every alternate price:
 [65000  1500  2500   450 11500 30000 45000  4000   750 15500 55000  3500
  6000]

5x5 TotalAmount matrix:
 [[65000  1000  1500 12000  5000]
 [64000  1350  1400 23000  2600]
 [30000  1600 45000 15000  8000]
 [29000   750 88000 15500  4200]
 [55000  2400  3500  3000 12000]]

Diagonal elements:
 [65000  1350 45000 15500 12000]


In [ ]:
# Q16: Create a correlation matrix between Quantity, Price, Rating, and TotalAmount using NumPy


q = np.array(df['Quantity'])
p = np.array(df['Price'])
r = np.array(df['Rating'])
t = np.array(df['TotalAmount'])

data = np.array([q, p, r, t])

corr=np.corrcoef(data)
corr


array([[ 1.        , -0.32498598, -0.2116622 , -0.15231468],
       [-0.32498598,  1.        ,  0.6723825 ,  0.93508518],
       [-0.2116622 ,  0.6723825 ,  1.        ,  0.68392943],
       [-0.15231468,  0.93508518,  0.68392943,  1.        ]])

In [134]:
# Calculate the covariance matrix
covar=np.cov(data)
covar

array([[ 3.33333333e-01, -3.99833333e+03, -7.50000000e-02,
        -2.17583333e+03],
       [-3.99833333e+03,  4.54098442e+08,  8.79366667e+03,
         4.93026967e+08],
       [-7.50000000e-02,  8.79366667e+03,  3.76666667e-01,
         1.03856667e+04],
       [-2.17583333e+03,  4.93026967e+08,  1.03856667e+04,
         6.12193892e+08]])

In [135]:
# Perform linear algebra operations: determinant and inverse of correlation matrix
det = np.linalg.det(corr)
print("Determinant:", det)

inv = np.linalg.inv(corr)
print("Inverse of Correlation Matrix:\n", inv)


Determinant: 0.04635211568692487
Inverse of Correlation Matrix:
 [[ 1.41910755  2.02006143  0.16191922 -1.78351991]
 [ 2.02006143 10.96689209 -0.26891808 -9.76337223]
 [ 0.16191922 -0.26891808  1.92814825 -1.04259334]
 [-1.78351991 -9.76337223 -1.04259334 10.57098865]]


In [ ]:
# Q18: Create a random array of 1000 sales values

sales=np.random.randint(1000,size=(10,100))
sales

array([[494, 424, 969, 162, 856,  47, 956, 398, 945, 930, 682, 430, 305,
        838, 145, 631, 509, 432, 956,  60, 770, 775, 983, 841, 285, 280,
        272, 431, 379, 768,  55,  34, 274, 506, 934, 375, 232, 761,   8,
        953, 352, 779, 361, 148, 830, 869, 328, 809, 377, 976, 543, 724,
        185, 144, 710,  94, 766, 392, 410, 281, 218, 879, 990, 385, 494,
        315,  66, 978, 201, 890, 892,  30, 169, 121,  87, 646, 516, 948,
        357,  37, 524, 930, 578, 731, 368, 988, 544, 605, 684, 423, 719,
        663, 421, 320, 861, 490, 343, 228, 609,  77],
       [306, 162, 533,  73, 811, 799, 170, 805, 642,  92, 216, 455, 742,
        483, 435, 860, 821, 150, 518, 672, 412,  89, 452, 177, 380, 229,
        885, 368, 647, 554, 579, 785,   1, 394, 369, 964, 548, 527, 700,
        331, 296, 911, 386, 912, 563, 909, 911, 205, 183, 739,  68, 436,
        637,  80, 398, 183, 472, 508, 893, 315,  77, 323, 888, 612, 722,
        760, 569, 778, 868, 283,   9,  79,  83, 905, 242, 547, 493, 70

In [142]:
# Use NumPy to flatten, reshape into (100, 10), and then transpose

sales.flatten()

array([494, 424, 969, 162, 856,  47, 956, 398, 945, 930, 682, 430, 305,
       838, 145, 631, 509, 432, 956,  60, 770, 775, 983, 841, 285, 280,
       272, 431, 379, 768,  55,  34, 274, 506, 934, 375, 232, 761,   8,
       953, 352, 779, 361, 148, 830, 869, 328, 809, 377, 976, 543, 724,
       185, 144, 710,  94, 766, 392, 410, 281, 218, 879, 990, 385, 494,
       315,  66, 978, 201, 890, 892,  30, 169, 121,  87, 646, 516, 948,
       357,  37, 524, 930, 578, 731, 368, 988, 544, 605, 684, 423, 719,
       663, 421, 320, 861, 490, 343, 228, 609,  77, 306, 162, 533,  73,
       811, 799, 170, 805, 642,  92, 216, 455, 742, 483, 435, 860, 821,
       150, 518, 672, 412,  89, 452, 177, 380, 229, 885, 368, 647, 554,
       579, 785,   1, 394, 369, 964, 548, 527, 700, 331, 296, 911, 386,
       912, 563, 909, 911, 205, 183, 739,  68, 436, 637,  80, 398, 183,
       472, 508, 893, 315,  77, 323, 888, 612, 722, 760, 569, 778, 868,
       283,   9,  79,  83, 905, 242, 547, 493, 702, 148, 871, 87

In [143]:
sales.reshape(100,10)

array([[494, 424, 969, 162, 856,  47, 956, 398, 945, 930],
       [682, 430, 305, 838, 145, 631, 509, 432, 956,  60],
       [770, 775, 983, 841, 285, 280, 272, 431, 379, 768],
       [ 55,  34, 274, 506, 934, 375, 232, 761,   8, 953],
       [352, 779, 361, 148, 830, 869, 328, 809, 377, 976],
       [543, 724, 185, 144, 710,  94, 766, 392, 410, 281],
       [218, 879, 990, 385, 494, 315,  66, 978, 201, 890],
       [892,  30, 169, 121,  87, 646, 516, 948, 357,  37],
       [524, 930, 578, 731, 368, 988, 544, 605, 684, 423],
       [719, 663, 421, 320, 861, 490, 343, 228, 609,  77],
       [306, 162, 533,  73, 811, 799, 170, 805, 642,  92],
       [216, 455, 742, 483, 435, 860, 821, 150, 518, 672],
       [412,  89, 452, 177, 380, 229, 885, 368, 647, 554],
       [579, 785,   1, 394, 369, 964, 548, 527, 700, 331],
       [296, 911, 386, 912, 563, 909, 911, 205, 183, 739],
       [ 68, 436, 637,  80, 398, 183, 472, 508, 893, 315],
       [ 77, 323, 888, 612, 722, 760, 569, 778, 868, 283

In [144]:
sales.T

array([[494, 306, 433, 904, 971, 491, 288, 518, 145,  49],
       [424, 162, 763, 523, 732,  26, 966, 473, 866,  96],
       [969, 533, 331, 279, 420, 894, 522, 467, 128, 279],
       [162,  73, 587, 849,  81, 999, 313, 401, 436, 462],
       [856, 811, 473, 373, 571, 340, 331, 156, 226, 142],
       [ 47, 799, 867, 991, 798, 339, 951,  17, 904, 766],
       [956, 170, 927, 691, 286, 916,  25, 120, 679, 491],
       [398, 805, 769, 797, 121, 479,  45, 356, 120, 177],
       [945, 642, 896, 422, 840, 874, 966, 396, 775, 283],
       [930,  92, 231, 365, 846, 732, 633, 339, 536, 255],
       [682, 216, 312, 660, 562, 812, 455, 750, 753, 329],
       [430, 455, 175, 734, 598, 858, 681,  32, 430, 165],
       [305, 742, 972, 255, 638,  69, 991, 979, 726, 119],
       [838, 483,  19, 506, 986, 818, 524,  50, 843, 342],
       [145, 435, 773, 419, 204, 889,   8, 620, 337, 388],
       [631, 860, 737,  41, 270, 662, 668,  34, 516, 874],
       [509, 821, 932, 441, 961, 878, 395,  36, 402, 630