In [4]:
import numpy as np

In [9]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
mat1

array([[1, 2],
       [3, 4]])

In [10]:
mat2

array([[5, 6],
       [7, 8]])

In [ ]:
#Multiplication
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [ ]:
#Transpose
mat1.T

array([[1, 3],
       [2, 4]])

In [ ]:
#determinants
np.linalg.det(mat1)

np.float64(-2.0000000000000004)

In [ ]:
#Inverse
np.linalg.inv(mat1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [16]:
original=np.array([1,2,3,4,5,6])
view=original.view()
copy=original.copy()

original[0]=99

print("Original Array:",original)
print("View Array (After changes):",view)
print("Copy Array:",copy)

Original Array: [99  2  3  4  5  6]
View Array (After changes): [99  2  3  4  5  6]
Copy Array: [1 2 3 4 5 6]
