In [2]:
import numpy as np


In [6]:
arr1=np.array([10,20,30,40,50])
print("1D Array:",arr1)

arr2=np.array([[1,2,3],[4,5,6]])
print("2D Array:",arr2)

arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D Array:",arr3)

arr3.ndim

1D Array: [10 20 30 40 50]
2D Array: [[1 2 3]
 [4 5 6]]
3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


3

In [8]:
arr2.shape

(2, 3)

In [9]:
arr2.size

6

In [10]:
arr2.dtype

dtype('int64')

In [ ]:
zeros= np.zeros((2,3))
ones=np.ones((3,2))
eye=np.eye(5)
rand=np.random.rand(2,3)
arge=np.arange(0,10,2)
linespace_arr=np.linspace(0,1,5)

print("\nZero Array:\n",zeros)
print("\nOnes Array:\n",ones)
print("\nIdentity Array:\n",eye)
print("\nArranged Array:\n",rand)
print("\nLinspace Array:\n",arge)
print("\nZero Array:\n",linespace_arr)


Zero Array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Identity Array:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Arranged Array:
 [[0.63558093 0.00800846 0.76985072]
 [0.28798721 0.40848327 0.12689204]]

Linespace Array:
 [0 2 4 6 8]

Zero Array:
 [0.   0.25 0.5  0.75 1.  ]


In [16]:
arr1[0]

np.int64(10)

In [17]:
arr1[1:3]

array([20, 30])

In [19]:
arr1[::2]

array([10, 30, 50])

In [20]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr2[1,2]

np.int64(6)

In [24]:
arr3[:2,:2]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
arr4=np.array([[10,20,30],[40,50,60],[70,80,90]])

arr4[:2,:2]

array([[10, 20],
       [40, 50]])

In [26]:
a=np.array([1,2,3])
b=np.array([4,5,6])

a+b

array([5, 7, 9])

In [27]:
a-b

array([-3, -3, -3])

In [28]:
a*b

array([ 4, 10, 18])

In [30]:
a/b

array([0.25, 0.4 , 0.5 ])

In [31]:
a**b

array([  1,  32, 729])

In [32]:
c=[[1,2,3],[4,5,6]]
d=[[7,8,9],[10,11,12]]

c+d

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [34]:
c*d

TypeError: can't multiply sequence by non-int of type 'list'

In [36]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
can=arr.reshape(3,4)

In [41]:
can.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

np.hstack((x,y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [46]:
np.vstack((x,y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [47]:
arr=np.array([5,10,15,20,25,30])
filter_arr=arr>15
print("\nFilter Boolen Array",filter_arr)
print("Filter Values(arr>15):", arr[filter_arr])


Filter Boolen Array [False False False  True  True  True]
Filter Values(arr>15): [20 25 30]


In [49]:
print("\nRandom Integer Between 1-100:",np.random.randint(1,100))
print("Random Float:",np.random.random())
print("Random 3x3 Matrix",np.random.randint(10,50,size=(3,3)))


Random Integer Between 1-100: 86
Random Float: 0.01260737729373429
Random 3x3 Matrix [[44 44 28]
 [43 18 11]
 [13 18 19]]
