In [ ]:
import pandas as pd
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import string
from nltk import word_tokenize

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential,load_model
from tensorflow.keras.layers import Embedding, Dense,Input,GlobalAveragePooling1D,Flatten,LSTM
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
from google.colab import files

print("Upload TRAIN file")
train_uploaded = files.upload()

print("Upload TEST file")
test_uploaded = files.upload()


Upload TRAIN file


Saving Corona_NLP_train.csv to Corona_NLP_train.csv
Upload TEST file


In [ ]:
import pandas as pd
train_df = pd.read_csv(r"/content/Corona_NLP_train (1).csv", encoding="latin-1")
test_df = pd.read_csv(r"/content/Corona_NLP_test.csv", encoding="latin-1")

print(train_df.head())
print(test_df.head())
print(test_df.head())

In [ ]:
train_df["Sentiment"].value_counts()

In [ ]:
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

wl = WordNetLemmatizer()
stp_wrds = stopwords.words("english")
translator = str.maketrans('', '', string.punctuation)

def clean_text(text):
    word_tok = word_tokenize(text)
    lemma_word = [wl.lemmatize(word, pos='v') for word in word_tok if word.lower() not in stp_wrds]
    lowercase_lemma_word = [word.lower() for word in lemma_word]
    processed_text = " ".join(lowercase_lemma_word).translate(translator).strip()
    return processed_text

In [ ]:
import nltk
nltk.download('stopwords')

In [ ]:
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

wl = WordNetLemmatizer()
stp_wrds = stopwords.words("english")
translator = str.maketrans('', '', string.punctuation)

def clean_text(text):
    word_tok = word_tokenize(text)
    lemma_word = [wl.lemmatize(word, pos='v') for word in word_tok if word.lower() not in stp_wrds]
    lowercase_lemma_word = [word.lower() for word in lemma_word]
    processed_text = " ".join(lowercase_lemma_word).translate(translator).strip()
    return processed_text

In [ ]:
import nltk
nltk.download('punkt_tab')

In [ ]:
import nltk
nltk.download('wordnet')


In [ ]:
text = "Hello, World! Python is amazing."
clean_text(text)


In [ ]:


train_df["Cleaned_tweet"] = train_df["OriginalTweet"].apply(lambda x:clean_text(x))

In [ ]:
train_df.head()

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment,Cleaned_tweet
0,3799,48751,London,16-03-2020,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,Neutral,menyrbie philgahan chrisitv https tcoifz9fa...
1,3800,48752,UK,16-03-2020,advice Talk to your neighbours family to excha...,Positive,advice talk neighbour family exchange phone nu...
2,3801,48753,Vagabonds,16-03-2020,Coronavirus Australia: Woolworths to give elde...,Positive,coronavirus australia woolworths give elderly...
3,3802,48754,NaN,16-03-2020,My food stock is not the only one which is emp...,Positive,food stock one empty please nt panic enough...
4,3803,48755,NaN,16-03-2020,"Me, ready to go at supermarket during the #COV...",Extremely Negative,ready go supermarket covid19 outbreak m para...


In [ ]:
X = train_df["Cleaned_tweet"].values
Y=  train_df["Sentiment"].values

In [ ]:
X

array(['menyrbie  philgahan  chrisitv https  tcoifz9fan2pa https  tcoxx6ghgfzcc https  tcoi2nlzdxno8',
       'advice talk neighbour family exchange phone number create contact list phone number neighbour school employer chemist gp set online shop account poss adequate supply regular meds order',
       'coronavirus australia  woolworths give elderly  disable dedicate shop hours amid covid19 outbreak https  tcobinca9vp8p',
       ...,
       'know itâ\x92s get tough  kameronwilds ration toilet paper  coronavirus  toiletpaper  kroger martinsville  help us',
       'wrong smell hand sanitizer start turn   coronavirus  covid19  coronavirus',
       'tartiicat well newused rift go  70000 amazon rn although normal market price usually  40000  prices really crazy right vr headsets since hl alex announce s worse covid19  whethe'],
      dtype=object)

In [ ]:
X[0]

'menyrbie  philgahan  chrisitv https  tcoifz9fan2pa https  tcoxx6ghgfzcc https  tcoi2nlzdxno8'

In [ ]:
X.shape

(41157,)

In [ ]:
Y

array(['Neutral', 'Positive', 'Positive', ..., 'Positive', 'Neutral',
       'Negative'], dtype=object)

In [ ]:
le = LabelEncoder()
Y=le.fit_transform(Y)

In [ ]:
Y

array([3, 4, 4, ..., 4, 3, 2])

In [ ]:
from keras.utils import to_categorical

In [ ]:
y_train = to_categorical(Y,num_classes =5 )

In [ ]:
y_train

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
tokenizer = Tokenizer(num_words = 50 ,oov_token ="<00V>")

In [ ]:
tokenizer.fit_on_texts(X)

In [ ]:
word_index = tokenizer.word_index

In [ ]:
word_index

{'<00V>': 1,
 'https': 2,
 'coronavirus': 3,
 'covid19': 4,
 'price': 5,
 'store': 6,
 'food': 7,
 'supermarket': 8,
 'grocery': 9,
 'people': 10,
 'amp': 11,
 'go': 12,
 'shop': 13,
 '19': 14,
 'consumer': 15,
 'get': 16,
 'covid': 17,
 'need': 18,
 's': 19,
 'online': 20,
 'buy': 21,
 'pandemic': 22,
 'time': 23,
 'work': 24,
 'hand': 25,
 'us': 26,
 'workers': 27,
 'help': 28,
 'stock': 29,
 'panic': 30,
 'make': 31,
 'nt': 32,
 'like': 33,
 'home': 34,
 'sanitizer': 35,
 'demand': 36,
 'say': 37,
 'take': 38,
 'see': 39,
 'supply': 40,
 'one': 41,
 'due': 42,
 'keep': 43,
 'mask': 44,
 'oil': 45,
 'new': 46,
 'please': 47,
 'stay': 48,
 'covid2019': 49,
 'use': 50,
 'crisis': 51,
 'toiletpaper': 52,
 'market': 53,
 'toilet': 54,
 'retail': 55,
 'think': 56,
 'paper': 57,
 'local': 58,
 'know': 59,
 'today': 60,
 'via': 61,
 'many': 62,
 'still': 63,
 'increase': 64,
 'shelve': 65,
 'delivery': 66,
 'stop': 67,
 '2': 68,
 'come': 69,
 'spread': 70,
 'impact': 71,
 'would': 72,
 'clo

In [ ]:
sequences = tokenizer.texts_to_sequences(X)

In [ ]:
sequences

[[1, 1, 1, 2, 1, 2, 1, 2, 1],
 [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  20,
  13,
  1,
  1,
  1,
  40,
  1,
  1,
  1],
 [3, 1, 1, 1, 1, 1, 1, 13, 1, 1, 4, 1, 2, 1],
 [7,
  29,
  41,
  1,
  47,
  32,
  30,
  1,
  7,
  1,
  38,
  18,
  48,
  1,
  48,
  1,
  1,
  4,
  4,
  3,
  1,
  1,
  1,
  2,
  1],
 [1,
  12,
  8,
  4,
  1,
  1,
  1,
  7,
  29,
  1,
  1,
  3,
  1,
  1,
  47,
  32,
  30,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  1],
 [1,
  1,
  1,
  1,
  4,
  1,
  1,
  1,
  1,
  1,
  1,
  10,
  1,
  1,
  6,
  1,
  1,
  40,
  25,
  35,
  7,
  1,
  1,
  1,
  1,
  1,
  2,
  1],
 [1, 9, 6, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1],
 [8, 1, 32, 21, 1, 1, 1, 1, 4, 2, 1],
 [42,
  4,
  1,
  6,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  20,
  1,
  1,
  1,
  1,
  1,
  2,
  1],
 [1,
  1,
  1,
  21,
  1,
  1,
  1,
  20,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  20,
  13,
  34,
  19,
  23,
  1,
  17,
  14,
  1,
  1],
 [1, 32, 

In [ ]:
padded = pad_sequences(sequences, maxlen=10,padding='post')
padded

array([[ 1,  1,  1, ...,  2,  1,  0],
       [ 1, 20, 13, ...,  1,  1,  1],
       [ 1,  1,  1, ...,  1,  2,  1],
       ...,
       [ 1,  1,  1, ...,  1, 28, 26],
       [ 1,  1, 25, ...,  4,  3,  0],
       [ 1,  1,  1, ...,  1,  4,  1]], dtype=int32)

In [ ]:
vocab_size = len(word_index)+1
embedding_dim = 16
max_len = 10

In [ ]:
model = Sequential()
model.add(Input(shape = padded[0].shape))
model.add(Embedding(input_dim= vocab_size,output_dim=embedding_dim))
model.add(GlobalAveragePooling1D())
model.add(Dense(32,activation="relu"))
model.add(Dense(16,activation="relu"))
model.add(Dense(5,activation="softmax"))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 10, 16)         │     1,306,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d        │ (None, 16)             │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │           544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 5)              │            85 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,307,941 (4.99 MB)

 Trainable params: 1,307,941 (4.99 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer="sgd",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
model.fit(padded,y_train,epochs=100,verbose=1)

NameError: name 'model' is not defined